FROM python:3.11.7

RUN pip install pandas sqlalchemy psycopg2

WORKDIR /app
COPY ingest_data.py ingest_data.py 
COPY green_tripdata_2019-09.csv green_tripdata_2019-09.csv
 
ENTRYPOINT [ "python", "ingest_data.py" ]